# Generated by Django 6.0.1 on 2026-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SUB_EXPIRING', 'Subscription Expiring'), ('SUB_EXPIRED', 'Subscription Expired'), ('SUB_RENEWED', 'Subscription Renewed'), ('COINS_ADDED', 'Coins Added'), ('NEW_POST', 'New Post')], max_length=50),
        ),
    ]
