# Generated by Django 6.0.1 on 2026-02-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0004_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SUB_EXPIRING', 'Subscription Expiring'), ('SUB_EXPIRED', 'Subscription Expired'), ('SUB_RENEWED', 'Subscription Renewed'), ('COINS_ADDED', 'Coins Added'), ('NEW_POST', 'New Post'), ('ROLE_CHANGED', 'Role Changed'), ('ACCOUNT_BLOCKED', 'Account Blocked')], max_length=50),
        ),
    ]
