# Generated by Django 6.0.1 on 2026-01-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_user_is_verified_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('publisher', 'Publisher'), ('admin', 'Admin'), ('support', 'Support')], default='user', max_length=10),
        ),
    ]
