# Generated by Django 6.0.1 on 2026-01-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_sitefeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteFeedback',
        ),
    ]
