# Generated by Django 6.0.1 on 2026-02-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
    ]
