apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: 420905172819.dkr.ecr.ap-south-1.amazonaws.com/django-service:latest
          imagePullPolicy: Always
          # In production, recommend using Gunicorn instead of runserver
          command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
          envFrom:
            - secretRef:
                name: django-secret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-backend
spec:
  selector:
    app: django-app
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: 420905172819.dkr.ecr.ap-south-1.amazonaws.com/django-service:latest
          command: ["celery", "-A", "Managmet", "worker", "-l", "info"]
          envFrom:
            - secretRef:
                name: django-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: 420905172819.dkr.ecr.ap-south-1.amazonaws.com/django-service:latest
          command: ["celery", "-A", "Managmet", "beat", "-l", "info"]
          envFrom:
            - secretRef:
                name: django-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-dashboard
  template:
    metadata:
      labels:
        app: flower-dashboard
    spec:
      containers:
        - name: flower
          image: 420905172819.dkr.ecr.ap-south-1.amazonaws.com/django-service:latest
          command: ["celery", "-A", "Managmet", "flower", "--port=5555"]
          envFrom:
            - secretRef:
                name: django-secret
          ports:
            - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: flower-dashboard
spec:
  selector:
    app: flower-dashboard
  ports:
    - port: 5555
