# Generated by Django 6.0.1 on 2026-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(help_text='Short book description')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(help_text='Upload book PDF', upload_to='books/pdfs/')),
                ('summary_text', models.TextField(help_text='Text used for explanation / AI voice')),
                ('voice_type', models.CharField(choices=[('manual', 'Manual Voice'), ('ai', 'AI Generated Voice')], default='manual', max_length=10)),
                ('audio_file', models.FileField(blank=True, help_text='Manual or AI generated audio file', null=True, upload_to='books/audio/')),
                ('language', models.CharField(default='English', help_text='Voice / book language', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='Books.category')),
            ],
        ),
    ]
