# Generated by Django 6.0.1 on 2026-01-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='books/audio/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary_text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Books.category')),
            ],
        ),
    ]
