# Generated by Django 6.0.1 on 2026-02-20 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_favoritebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(help_text='Short book description')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(upload_to='books/submissions/pdfs/')),
                ('summary_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified by AI'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_report', models.JSONField(blank=True, default=dict)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Books.category')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
