# Generated by Django 6.0.1 on 2026-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_booksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='suggested_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
