# Generated by Django 6.0.1 on 2026-02-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_booksubmission_suggested_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksubmission',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/submissions/covers/'),
        ),
    ]
