# Generated by Django 6.0.1 on 2026-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_booksubmission_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio_file',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='booksubmission',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='booksubmission',
            name='pdf_file',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
