# Generated by Django 6.0.1 on 2026-02-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefeedback',
            name='comment',
            field=models.CharField(max_length=50),
        ),
    ]
