# Generated by Django 6.0.1 on 2026-02-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_alter_sitefeedback_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefeedback',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
