# Generated by Django 6.0.1 on 2026-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_alter_sitefeedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1),
        ),
    ]
